More work to clean up parser.  Makefile tweaks.

diff --git a/test/suite/functions/Makefile b/test/suite/functions/Makefile
--- a/test/suite/functions/Makefile
+++ b/test/suite/functions/Makefile
@@ -17,7 +17,7 @@ positive-tests:
 	do \
 	  ( echo "running $$TEST..."; \
 	  $(CMIX) -f $${TEST}.sco; \
-	  if [ $$? -eq 0 ]; then echo "SCORE PASSED"; else echo "SCORE FAILED"; fi ); \
+	  if [ $$? -eq 0 ]; then echo "SCORE PASSED"; else echo "SCORE '$${TEST}.sco' FAILED" && exit -1; fi ); \
 	done
 
 compat-tests:
@@ -25,7 +25,7 @@ compat-tests:
 	do \
 	  ( echo "running $$TEST..."; \
 	  $(CMIX) -f $${TEST}.sco; \
-	  if [ $$? -eq 0 ]; then echo "SCORE PASSED"; else echo "SCORE FAILED"; fi ); \
+	  if [ $$? -eq 0 ]; then echo "SCORE PASSED"; else echo "SCORE $${TEST}.sco FAILED" && exit -1; fi ); \
 	done
 
 block-tests:
@@ -33,7 +33,7 @@ block-tests:
 	do \
 	  ( echo "running $$TEST..."; \
 	  $(CMIX) -f $${TEST}.sco; \
-	  if [ $$? -eq 0 ]; then echo "SCORE PASSED"; else echo "SCORE FAILED"; fi ); \
+	  if [ $$? -eq 0 ]; then echo "SCORE PASSED"; else echo "SCORE $${TEST}.sco FAILED" && exit -1; fi ); \
 	done
 
 func-tests:
@@ -41,7 +41,7 @@ func-tests:
 	do \
 	  ( echo "running $$TEST..."; \
 	  $(CMIX) -f $${TEST}.sco; \
-	  if [ $$? -eq 0 ]; then echo "SCORE PASSED"; else echo "SCORE FAILED"; fi ); \
+	  if [ $$? -eq 0 ]; then echo "SCORE PASSED"; else echo "SCORE $${TEST}.sco FAILED" && exit -1; fi ); \
 	done
 
 # Tests which should fail
@@ -51,8 +51,6 @@ negative-tests:
 	do \
 	  ( echo "running $$TEST..."; \
 	  $(CMIX) -f $${TEST}.sco; \
-	  if [ $$? -eq 0 ]; then echo "SCORE FAILED (BY NOT FAILING)"; else echo "SCORE PASSED (BY CORRECTLY FAILING)"; fi ); \
+	  if [ $$? -eq 0 ]; then echo "SCORE $${TEST}.sco FAILED (BY NOT FAILING)" && exit -1; else echo "SCORE PASSED (BY CORRECTLY FAILING)"; fi ); \
 	done
-
-
 
diff --git a/test/suite/parser/Makefile b/test/suite/parser/Makefile
--- a/test/suite/parser/Makefile
+++ b/test/suite/parser/Makefile
@@ -41,6 +41,7 @@ FAIL_SCORES = \
 func_errortests1.sco \
 handletest1.sco \
 include_error.sco \
+nested_func_decls.sco \
 struct_duplicate_member.sco \
 struct_duplicate_membername.sco \
 struct_init_wrong_type.sco \
@@ -53,7 +54,7 @@ scores_that_pass:
         do \
           ( echo "running $$SCORE..."; \
           $(CMIX) -f $$SCORE; \
-		  if [ $$? -eq 0 ]; then echo "SCORE PASSED"; else echo "SCORE FAILED"; fi ); \
+		  if [ $$? -eq 0 ]; then echo "SCORE PASSED"; else echo "SCORE '$$SCORE' FAILED" && exit -1; fi ); \
         done
 
 scores_that_fail:
@@ -61,7 +62,7 @@ scores_that_fail:
         do \
           ( echo "running $$SCORE..."; \
           $(CMIX) -f $$SCORE; \
-		  if [ $$? -eq 0 ]; then echo "SCORE FAILED (BY NOT FAILING)"; else echo "SCORE PASSED (BY CORRECTLY FAILING)"; fi ); \
+		  if [ $$? -eq 0 ]; then echo "SCORE '$$SCORE' FAILED (BY NOT FAILING)" && exit -1; else echo "SCORE PASSED (BY CORRECTLY FAILING)"; fi ); \
         done
 
 all:	scores_that_pass scores_that_fail
